version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-pg:/var/lib/postgresql/data
  pgtask:
    build: .
    depends_on:
      - db
    image: pgtask:latest
    ports:
      - '8080:8080'

volumes:
  db-pg:
    driver: local
