micronaut:
  application:
    name: pgtask
  http:
    services:
      stackexchange:
        url: 'https://api.stackexchange.com/2.3'
  caches:
    user-cache:
      expire-after-write: P1D
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://${DBHOST}:${DBPORT}/pgdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml
